@extends('app')

@section('content')
    <section id="content">
        <div class="ui container">
            <div class="head"><i class="icon code"></i> Web/Mobile <div class="green"></div><div class="red"></div></div>
            <div class="ui segment">
                  


                <div class="col-xs-12 ">
                            <nav>
                                <div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist">
                                    <a class="nav-item nav-link active" id="nav-anunt-tab" data-toggle="tab" href="#nav-anunt" role="tab" aria-controls="nav-anunt" aria-selected="true">Anunturi</a>
                                    <a class="nav-item nav-link" id="nav-reg-tab" data-toggle="tab" href="#nav-reg" role="tab" aria-controls="nav-reg" aria-selected="false">Regulament</a>
                                    <a class="nav-item nav-link" id="nav-rez-tab" data-toggle="tab" href="#nav-rez" role="tab" aria-controls="nav-rez" aria-selected="false">Editia anterioara</a>
                                </div>
                            </nav>
                            <div class="tab-content py-3 px-3 px-sm-0" id="nav-tabContent">
                                <div class="tab-pane fade show active" id="nav-anunt" role="tabpanel" aria-labelledby="nav-anunt-tab">
                                <br><center><h2>FII Code - Web/Mobile</h2>
	<br>
	Aceasta pagina este dedicata sectiunii de web/mobile din cadrul concursului FII Code. Aici se vor posta informatiile utile participantilor la aceasta sectiune.

	<br>
	<br>
    <b>Calendar proba Web/Mobile</b><br><br>

	
		Runda online - 25 ianuarie - 29 martie 2019 		<br>
		Runda Finala - 13 aprilie 2019		<br>
	</center>

</div>
<div class="tab-pane fade" id="nav-reg" role="tabpanel" aria-labelledby="nav-reg-tab">
<p style="line-height: 1.54284; margin-top: 0pt; margin-bottom: 4pt;"><span style="font-size: 26pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">Regulamentul secțiunii Web &amp; Mobile</span></p>
<p style="line-height: 1.7142000000000002; margin-top: 0pt; margin-bottom: 11pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">Concursul național de informatică FIICode este organizat de către Facultatea de Informatică Iași și Asociația Studenților Informaticieni Ieșeni (ASII), &icirc;n parteneriat cu Inspectoratul Școlar Județean Iași.</span></p>
<h2 style="line-height: 1.7142000000000002; margin-top: 18pt; margin-bottom: 11pt;"><span style="font-size: 16pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">Obiective</span></h2>
<p style="line-height: 1.7142000000000002; margin-top: 0pt; margin-bottom: 11pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">&Icirc;n cadrul probei de Tehnologii Web &amp; Mobile se urmărește dezvoltarea:</span></p>
<ul style="margin-top: 0pt; margin-bottom: 0pt;">
<li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre; margin-left: 45pt;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor=""><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">aptitudinilor și competențelor de utilizare a tehnologiilor Web sau Mobile existente</span></li>
<li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre; margin-left: 45pt;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor=""><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">abilităților de comunicare, lucru &icirc;n echipă și management al timpului</span></li>
<li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre; margin-left: 45pt;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor=""><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">abilităților de susținere, &icirc;n fața unui juriu avizat, a unui proiect propriu</span></li>
</ul>
<p><br /><br /></p>
<h2 style="line-height: 1.7142000000000002; margin-top: 18pt; margin-bottom: 11pt;"><span style="font-size: 16pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">Participanți</span></h2>
<p style="line-height: 1.7142000000000002; margin-top: 0pt; margin-bottom: 11pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">Participarea la concurs se face &icirc;n echipe formate dintr-un număr de 2-3 concurenți, &icirc;nscriși la momentul &icirc;nceperii concursului la un liceu sau facultate din Rom&acirc;nia, indiferent de naționalitate.Fiecare echipă va fi identificată printr-un număr unic de concurs.</span></p>
<h2 style="line-height: 1.7142000000000002; margin-top: 18pt; margin-bottom: 11pt;"><span style="font-size: 16pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">Etape</span></h2>
<ul style="margin-top: 0pt; margin-bottom: 0pt;">
<li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre; margin-left: 45pt;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor=""><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">Etapa Online: 25 Ianuarie - 29 Martie</span></li>
<li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre; margin-left: 45pt;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor=""><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">Etapa Finală: 12-14 Aprilie</span></li>
</ul>
<p>&nbsp;</p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">Etapa online constă &icirc;n realizarea unui proiect. &icirc;n conformitate cu tema și specificațiile Comisiei de la secțiunea de Tehnologii Web &amp; Mobile. Proiectul va fi gestionat de una din platformele GitHub, GitLab sau BitBucket pe intreaga perioada a concursului FIICode, astfel &icirc;nc&acirc;t comisia să aiba acces la resursele fiecarui proiect (cod sursa, artefacte etc.). </span></p>
<p style="line-height: 1.7142000000000002; margin-top: 0pt; margin-bottom: 11pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">După această etapă, proiectele vor fi jurizate de către Comisie, urm&acirc;nd să se anunțe cele 3 echipe finaliste.</span></p>
<p style="line-height: 1.7142000000000002; margin-top: 0pt; margin-bottom: 11pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">Etapa finală constă &icirc;ntr-o probă practică desfasurata la Facultatea de Informatica pe baza specificațiilor Comisiei.</span></p>
<p>&nbsp;</p>
<h2 style="line-height: 1.7142000000000002; margin-top: 18pt; margin-bottom: 11pt;"><span style="font-size: 16pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">&Icirc;nscriere</span></h2>
<p style="line-height: 1.7142000000000002; margin-top: 0pt; margin-bottom: 11pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">Inscrierile se pot face pana pe data de 24 ianuarie. Atunci c&acirc;nd completează formularul de &icirc;nscriere, echipa trebuie sa furnizeze informații corecte și complete. După &icirc;nscriere, fiecare echipă va avea un nume de utilizator și o parolă cu care va trimite proiectul spre jurizare. </span></p>
<p style="line-height: 1.7142000000000002; margin-top: 0pt; margin-bottom: 11pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">La finalul etapei online, fiecare proiect va fi evaluat conform criteriilor de jurizare, obtinandu-se o ierarhie a echipelor participante. Primele 3 clasate vor putea praticipa la etapa finala.</span></p>
<h2 style="line-height: 1.7142000000000002; margin-top: 18pt; margin-bottom: 11pt;"><span style="font-size: 16pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">Participare</span></h2>
<p style="line-height: 1.7142000000000002; margin-top: 0pt; margin-bottom: 11pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">Odată anunțată lista cu echipele participante la etapa finală, acestea au la dispoziție o săptăm&acirc;nă pentru a confirma prezența. &Icirc;n cazul &icirc;n care o echipă, din orice motive, nu poate participa la această etapă, dreptul de participare va fi oferit următoarei echipe clasate.</span></p>
<p>&nbsp;</p>
<h2 style="line-height: 1.7142000000000002; margin-top: 18pt; margin-bottom: 11pt;"><span style="font-size: 16pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">Tehnologii și instrumente</span></h2>
<p style="line-height: 1.7142000000000002; margin-top: 0pt; margin-bottom: 11pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">Pentru realizarea proiectelor vor fi admise orice tehnologie, instrument, platformă, limbaj de programare.</span></p>
<p><br /><br /></p>
<h2 style="line-height: 1.7142000000000002; margin-top: 18pt; margin-bottom: 11pt;"><span style="font-size: 16pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">Comisie</span></h2>
<p style="line-height: 1.7142000000000002; margin-top: 0pt; margin-bottom: 11pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">Comisia de la proba de Tehnologii Web este formată din:</span></p>
<ul style="margin-top: 0pt; margin-bottom: 0pt;">
<li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre; margin-left: 45pt;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor=""><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">președinte, </span></li>
<li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre; margin-left: 45pt;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor=""><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">coordonatorul probei </span></li>
<li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre; margin-left: 45pt;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor=""><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">reprezentanți ai companiilor partenere Platinum</span></li>
</ul>
<p><br /><br /></p>
<h2 style="line-height: 1.7142000000000002; margin-top: 18pt; margin-bottom: 11pt;"><span style="font-size: 16pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">Evaluare</span></h2>
<p style="line-height: 1.7142000000000002; margin-top: 0pt; margin-bottom: 11pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">La finalul probei online, Comisia va evalua solutia propusa de fiecare echipa participanta conform urmatoarelor criterii</span></p>
<ul style="margin-top: 0pt; margin-bottom: 0pt;">
<li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor=""><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">50% Rezolvarea integrală a problemei &ndash; conform cerinţelor specificate</span></li>
<li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor=""><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">20% Gradul de creativitate a soluţiei furnizate.(interfata cu utilizatorul, asigurarea experienta utilizatorului, maniere de interactiune)</span></li>
<li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor=""><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">20% Lucrul in echipa + folosirea continua a depozitului de cod asociat proiectului de catre toti membrii echipei</span></li>
<li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor=""><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">10% Prezentarea solutiei (video)</span></li>
</ul>
<p>&nbsp;</p>
<p style="line-height: 1.7142000000000002; margin-top: 0pt; margin-bottom: 11pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">In ceea ce priveste proba finala, criteriile de valuare sunt:</span></p>
<ul style="margin-top: 0pt; margin-bottom: 0pt;">
<li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor=""><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">50% Rezolvarea integrală a problemei &ndash; conform cerinţelor specificate</span></li>
<li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor=""><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">30% Gradul de creativitate a soluţiei furnizate</span></li>
<li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor=""><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">20% Prezentarea publica a solutiei</span></li>
</ul>
<p style="line-height: 1.7142000000000002; margin-top: 0pt; margin-bottom: 11pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">Punctajul total va reprezenta media ponderata dintre punctajul obtinut la etapa online (40%) si punctajul acordat la proba finala (60%).</span></p>
<h2 style="line-height: 1.7142000000000002; margin-top: 18pt; margin-bottom: 11pt;"><span style="font-size: 16pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">Rezultate</span></h2>
<p>&nbsp;</p>
<p style="line-height: 1.7142000000000002; margin-top: 0pt; margin-bottom: 11pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor=""> Fiecare finalist va primi o diplomă de participare. Premiile I, II si III vor fi oferite &icirc;n cadrul festivității de premiere.</span></p>
<p>&nbsp;</p>
<h2 style="line-height: 1.7142000000000002; margin-top: 18pt; margin-bottom: 11pt;"><span style="font-size: 16pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">Descalificare</span></h2>
<p style="line-height: 1.7142000000000002; margin-top: 0pt; margin-bottom: 11pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">O echipă care:</span></p>
<ul style="margin-top: 0pt; margin-bottom: 0pt;">
<li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre; margin-left: 45pt;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor=""><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">interferează cu activitățile altor participanți,</span></li>
<li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre; margin-left: 45pt;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor=""><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">deterioareaza &nbsp;echipamentele sau salile in care se desfasoara competitia ,</span></li>
<li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre; margin-left: 45pt;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor=""><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">prezinta un comportament neadecvat pe parcursul concursului </span></li>
<li style="list-style-type: disc; font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre; margin-left: 45pt;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor=""><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">fraudează concursul sau instigă la fraudă prin orice mijloc (inclusiv electronic) va fi descalificată fără drept de re&icirc;nscriere a membrilor acesteia.</span></li>
</ul>
<p>&nbsp;</p>
<p style="line-height: 1.7142000000000002; margin-top: 0pt; margin-bottom: 11pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">Coordonatorul concursului &icirc;și rezervă dreptul de a descalifica fără notificare prealabilă și fără drept de contestație participanții aflați &icirc;ntr-o situație de descalificare identificată. Pentru a descalifica o echipă, este necesar acordul coordonatorului concursului și cel al coordonatorului ariei de concurs.</span></p>
<p style="line-height: 1.7142000000000002; margin-top: 0pt; margin-bottom: 11pt;"><span style="font-size: 10.5pt; font-family: Arial; color: #434d56; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;" data-darkreader-inline-color="" data-darkreader-inline-bgcolor="">.</span></p>


                                </div>
                                <div class="tab-pane fade" id="nav-rez" role="tabpanel" aria-labelledby="nav-rez-tab">
                                    <br><center><h2><strong>Teme din editia 2018:</strong></h2><br><br>
                                    <p>
                                    Să se realizeze o aplicație Web/Mobile care să ofere o interfață prietenoasă ce să asiste persoanele cu diverse alergii. Aplicația va fi capabilă să gestioneze (tipuri de) alergii și să notifice o persoană sau un grup de utilizatori asupra apariției unei alergii sezoniere (ex.: la polen, expunere directă la soare sau la praf, etc.), eventual în conjuncție cu anumite fructe sau compuși alimentari, și/sau conform unor condiții de mediu (ex.: temperatură, umezeală, etc.). Notificările vor fi semnalate, inclusiv cu o anumită prioritate/frecvență, atât în cadrul aplicației cât și pe un dispozitiv mobil (telefon, tabletă) al utilizatorului sau a unei persoane de contact. Se vor pune la dispoziție, de asemenea, sfaturi referitoare la preîntâmpinarea unei/unor alergii, plus tratamentul și/sau medicația. Utilizatorii îți vor putea adăuga alergiile, cu posibilitatea de a fi partajate la nivel de grup, inclusiv la nivelul unei rețele sociale. Diversele statistici de interes vor fi oferite via vizualizări atractive, iar interacțiunea cu utilizatorul va putea fi efectuată și prin intermediul unui agent de infață conversațional.
                                    </p>
                                    <br><b>Clasament:</b><br><br>
                                    
                                        1.<b>Discode</b><br>
                                        2.<b>CVA Team</b><br>
                                        3.<b>DMSL</b><br>
                                        4.<b>In a nutshell</b><br>
                                        5.<b>Codeleign</b><br>
                                        6.<b>Rufus</b> -Necalificata pentru runda finala.<br>
                                        7.<b>Blank</b> -Necalificata pentru runda finala.<br>

                                    
                                    </center>
                                </div>

                
                </div>
                </div>
            <div class="ui container"></div>
        </div>
    </section>
@endsection
